### ISSUE TITLE
Create a one Card Game...

### ISSUE THREAD

**Issue by cat2k22** [cat2k22/Hactoberfest2022#1]

**Comment by unknown2K21** [comment]
Hi, Please assign me this issue...

**Comment by cat2k22** [comment]
Ok, i will assign this issue.

**Comment by unknown2K21** [comment]
Can, you please give some description. so, it will help me to complete this one.

**Comment by cat2k22** [comment]
Just, create one simple card game...

**Comment by cat2k22** [comment]
Issue is resolved. Thank you

**Comment by cat2k22** [comment]
Thank you
