### ISSUE TITLE
simple Validation for login page

### ISSUE THREAD

**Issue by cat2k22** [cat2k22/Hactoberfest2022#15]
Validation is required

**Comment by Mannu292001** [comment]
pls assign to me

**Comment by pallavi2031** [comment]
hey @cat2k22 may you please assign this issue I want to contribute.

**Comment by saksham-tiwari** [comment]
@cat2k22 I want to work on this issue, can you assign it to me? Can do it within next couple of hours.

**Comment by cat2k22** [comment]
Ok, i will assign you

**Comment by cat2k22** [comment]
> hey @cat2k22 may you please assign this issue I want to contribute.

I will assign you

**Comment by cat2k22** [comment]
> pls assign to me

I will assign you.

**Comment by unknown2k21** [comment]
Please, assign me this issue. i will work on this issue.

**Comment by cat2k22** [comment]
> Please, assign me this issue. i will work on this issue.

Ok, i will assign you.
