### ISSUE TITLE
Develop one weather app using html, css, js

### ISSUE THREAD

**Issue by cat2k22** [cat2k22/Hactoberfest2022#17]
if guys anyone have doubts on this issue. please, comment

**Comment by melencholicmice** [comment]
i would like to take up this issue, can you please assign it to me.

**Comment by unknown2k21** [comment]
Please, assign me this issue.

**Comment by cat2k22** [comment]
> Please, assign me this issue.

ok, i will assign you

**Comment by cat2k22** [comment]
> i would like to take up this issue, can you please assign it to me.

okay i'll assigning you.
